### ISSUE TITLE
GraphicsWindow.LastKey always returns null 

### ISSUE THREAD

**Issue by nonkit** [sb/smallbasic-editor#106]
GraphicsWindow.LastKey always returns "".

**Comment by nonkit** [comment]
Please refer [Small Basic: Key Input](https://social.technet.microsoft.com/wiki/contents/articles/29850.small-basic-key-input.aspx) to know how SBD works.

**Comment by Caseysch** [comment]
Could not get KeyDown to work at all. Clicking the white space generated events, but not pressing keys.

```
GraphicsWindow.MouseDown = OnMouseDown
GraphicsWindow.KeyDown = OnKeyDown

Sub OnKeyDown
    TextWindow.WriteLine("key was pressed.")
EndSub

Sub OnMouseDown
    TextWindow.WriteLine("mouse was clicked.")
EndSub
```

**Comment by nonkit** [comment]
Thank you @Caseysch for reporting details.  But the value of GraphicsWindow.Lastkey and calling key down event may be different issue.  So I will file new issue for the key down event.  Thanks.
