### ISSUE TITLE
Setting GraphicsWindow.Width and Height causes syntax error

### ISSUE THREAD

**Issue by nonkit** [sb/smallbasic-editor#113]
Following code causes syntax error "Property 'GraphicsWindow.Width/Height' cannot be assigned to. It is ready only".  ("read only" may be correct.)  This error prevent to run many existing programs for SBD (Small Basic Desktop).  Do nothing with following code may help to run many existing programs for SBD.
```
GraphicsWindow.Width = 600
GraphicsWIndow.Height = 400
```
This issue is filed to recognize SBD parity.

**Comment by Caseysch** [comment]
A lot of existing sample code uses these lines
