### ISSUE TITLE
Default of FontBold is "False"

### ISSUE THREAD

**Issue by nonkit** [sb/smallbasic-editor#126]
This is SBD 1.2/1.3 parity issue.  Default value of GraphicsWindow.FontBold is "True" in SBD.  But Default value of GraphicsWindow.FontBold is "False" in SBO 1.0.

Sample code to reproduce this issue is
```
GraphicsWindow.BrushColor = "Black"
GraphicsWindow.FontSize = 20
GraphicsWindow.DrawText(10, 10, "Default")
GraphicsWindow.FontBold = "True"
GraphicsWindow.DrawText(10, 40, "FontBold = True")
GraphicsWindow.FontBold = "False"
GraphicsWindow.DrawText(10, 70, "FontBold = False")
```
Result in SBO 1.0:
![FontBold SBO](https://user-images.githubusercontent.com/9944452/75996672-8c533e00-5f41-11ea-9f27-241ba4706003.png)

Result in SBD 1.2:
![FontBold SBD](https://user-images.githubusercontent.com/9944452/75996692-96753c80-5f41-11ea-85d7-408d53444310.png)

**Comment by OmarTawfik** [comment]
Closed by #141
