### ISSUE TITLE
Some of spaces will be lost in text literals

### ISSUE THREAD

**Issue by nonkit** [sb/smallbasic-editor#129]
Sample code 1 - will lost all leading spaces.
```
TextWindow.WriteLine("  *  ")
TextWindow.WriteLine(" *** ")
TextWindow.WriteLine("*****")
```
Sample code 2 - will lost the first leading spaces and other spaces becomes one space. 
```
TextWindow.Write("  *  ")
TextWindow.Write(" *** ")
TextWindow.Write("*****")
```
GraphicsWindow.DrawText will lost spaces as well.

**Comment by OmarTawfik** [comment]
Fixed by #142
