### ISSUE TITLE
Level 1 Tutorial should work 

### ISSUE THREAD

**Issue by Caseysch** [sb/smallbasic-editor#133]
'Challenges from the end of the tutorial would go here
'You have to set these BEFORE the turtle starts moving
GraphicsWindow.PenColor = GraphicsWindow.GetRandomColor()
Turtle.Speed = 7

'Lesson 2: Hello, Turtle
Turtle.Show()

'Lesson 3: Let's Give Turtle Something to Do
GraphicsWindow.DrawImage("https://aka.ms/mz1", 0, 0)
Turtle.X = 50
Turtle.Y = 50

'Lesson 4: Get Moving!
Turtle.TurnRight()
Turtle.Move(200)
Turtle.TurnRight()

Turtle.Move(150)
Turtle.TurnRight()
Turtle.Move(200)
Turtle.TurnLeft()
Turtle.Move(50)

' Challenge: Celebration dance (this is my dance, what's yours?)
Turtle.TurnLeft()
Turtle.TurnRight()
Turtle.TurnRight()
Turtle.TurnLeft()

**Comment by Caseysch** [comment]
#107 looks like the only issue

**Comment by Ed-Price** [comment]
As #107 is now closed (and verifying with the originator), we'll close this bug category (for the Level 1 Tutorial to work as expected).
