### ISSUE TITLE
TextWindow - Read Input cursor should be in focus on TextWindow by default

### ISSUE THREAD

**Issue by Ed-Price** [sb/smallbasic-editor#15]
The TextWindow in run time requires a focus change in Chrome, Edge, and IE (you have to click on the 'terminal' or TextWindow to enter input) - some younger students may struggle with the 'focus'/active window element. Also, this is a feature in the current version of SBO (http://aka.ms/SBOnline) as well as in SB Desktop. So it's a parity issue. (Issue from Council member Marcus T.)

**Comment by OmarTawfik** [comment]
@EdPrice-MSFT thanks for submitting!
will submit a fix soon.
