### ISSUE TITLE
Math.getRandomNumber returns a zero ( 0 ) 

### ISSUE THREAD

**Issue by mtwyford** [sb/smallbasic-editor#17]
I ran the students through a couple labs yesterday - did not do a thorough test - but saw that Math.getRandomNumber - that takes the max number as an argument and should return a number between 1 and the max number was returning a 0 (zero)
I was seeing effect about half of the students/users
I sat down to write a quick test this morning - but the site is presently down.

**Comment by OmarTawfik** [comment]
Thanks @mtwyford for reporting!
