### ISSUE TITLE
DrawRectangle and FillRectangle always draw the left of the rectangle at x=0

### ISSUE THREAD

**Issue by ozjerry** [sb/smallbasic-editor#18]
The Public Preview of version 1.0 has an error in it's rectangle drawing methods on the GraphicsWindow.

The following code should draw all shapes 100 pixels in from the left hand edge. The ellipse is drawn in the correct spot, but the two rectangles are drawn with their left edge at zero.

`GraphicsWindow.BackgroundColor = "steelblue"`
`GraphicsWindow.DrawEllipse(100, 30, 20, 20)`
`GraphicsWindow.DrawRectangle(100, 100, 100, 50)`
`GraphicsWindow.FillRectangle(100, 170, 100, 50)`

This appears to be the same regardless of the x value.
The above code works fine in V0.91

**Comment by OmarTawfik** [comment]
@ozjerry thanks for reporting! will submit a fix soon.
