### ISSUE TITLE
GraphicsWindow only renders when program finishes, 

### ISSUE THREAD

**Issue by ozjerry** [sb/smallbasic-editor#19]
In V0.91 the following code does what you would expect and renders 10 ellipses, and then proceeds to move one every 500ms.

But in V1.0 preview sometimes nothing is rendered to the graphics window until the program is finished, and sometimes it will render the initial position and then change them all to the final position in one hit when the program ends. The count is still printed to the textWindow so you can see that the program is executing, but no graphics are rendered. So it's currently not possible to do any proper animation in V1.0.

`n = 10`

`for i = 1 to n`
`    circles[i] = Shapes.AddEllipse(10, 10)`
`    Shapes.Move(circles[i], Math.GetRandomNumber(400), Math.GetRandomNumber(400))`
`EndFor`

`for i = 1 to 10`
`    TextWindow.WriteLine(i)`
`    Shapes.Move(circles[i], Math.GetRandomNumber(400), Math.GetRandomNumber(400))`
`    Program.Delay(500)`
`EndFor`

**Comment by OmarTawfik** [comment]
@ozjerry thanks for reporting!
Will submit a fix soon.
