### ISSUE TITLE
Ellipse position is more right and lower

### ISSUE THREAD

**Issue by nonkit** [sb/smallbasic-editor#33]
Following operations put ellipses x-radius more right and y-radius lower.

- GraphicsWindow.DrawEllipse
- GraphicsWindow.FillEllipse
- Shapes.AddEllipse
- Shapes.Move

Sample program to reproduce this issue is GKL260 (SBD).

**Comment by OmarTawfik** [comment]
Thanks @nonkit for the report! For future reference, can you please put the repro in the bug report betweek "```" tags?

Example:
```
' Ellipse Test for SBO v1.0
' Copyright © Nonki Takahashi.  The MIT License.

For y = 0 To 600 Step 100
    Shapes.AddLine(0, y, 800, y)
EndFor
For x = 0 To 800 Step 100
    Shapes.AddLine(x, 0, x, 600)
EndFor
GraphicsWindow.FillEllipse(100, 100, 100, 100)
GraphicsWindow.DrawEllipse(100, 100, 100, 100)
shp = Shapes.AddEllipse(100, 100)
Program.Delay(1000)
Shapes.Move(shp, 0, 0)
shp = Shapes.AddEllipse(100, 100)
Program.Delay(1000)
Shapes.Move(shp, 100, 0)
shp = Shapes.AddEllipse(100, 100)
Program.Delay(1000)
Shapes.Move(shp, 0, 100)
```

**Comment by nonkit** [comment]
> For future reference, can you please put the repro in the bug report betweek "```" tags?

OK I'll do that.  Thanks.
