### ISSUE TITLE
Text.GetSubText sometimes stops the program

### ISSUE THREAD

**Issue by nonkit** [sb/smallbasic-editor#35]
Some parameter such as Text.GetSubText(txt, 2, 2) stops the program.  With [Debug] button, [Pause] button will appear.  Sample code to reproduce this issue is:

txt = "123456789"
subtxt = Text.GetSubText(txt, 2, 2)
TextWindow.WriteLine(subtxt)

**Comment by OmarTawfik** [comment]
thanks @nonkit for reporting! will submit a fix.
