### ISSUE TITLE
Some tests failing with different CultureInfo setting

### ISSUE THREAD

**Issue by alxnull** [sb/smallbasic-editor#42]
My OS is set to German language which uses "," instead of "." as decimal separator. This causes some tests to fail on my machine because floating point numbers are converted to string according to the current culture settings but compared to strings with "." as separator. One example:

> Expected values to be 
"
ar = 1=2;
x = 2.5", but 
"
ar = 1=2;
x = 2,5" differs near ",5" (index 18).

Maybe InvariantCulture could be set explicitly for executing the tests?

**Comment by OmarTawfik** [comment]
That makes sense. Do you mean formatting in the affected tests? I don't know if this can be set globally.
