### ISSUE TITLE
DBCS name causes syntax error

### ISSUE THREAD

**Issue by nonkit** [sb/smallbasic-editor#47]
DBCS variable/subroutine/label names cause syntax errors.  Sample code to reproduce:
```
ラベル:
サブ()
TextWindow.WriteLine(変数)
Goto ラベル

Sub サブ
  変数 = Math.GetRandomNumber(100)
EndSub
```

**Comment by OmarTawfik** [comment]
Thanks @nonkit for reporting!
Will submit a fix soon.
