### ISSUE TITLE
MouseY Measuring from top of window rather than top of canvas

### ISSUE THREAD

**Issue by ozjerry** [sb/smallbasic-editor#56]
In V.01, reading the MouseY position using either GraphicsWindow.MouseY or Mouse.MouseY results in a value that is roughly 200px to high.

It looks as if it is using the offset from the top of the window, rather than the top of the canvas. 

The following code demonstrates the problem:

```
GraphicsWindow.MouseMove = mouseMove


Sub mouseMove
    GraphicsWindow.Clear()
    GraphicsWindow.DrawText(10, 10, GraphicsWindow.MouseX)
    GraphicsWindow.DrawText(40, 10, Mouse.MouseX)
    GraphicsWindow.DrawText(10, 40, GraphicsWindow.MouseY)
    GraphicsWindow.DrawText(40, 40, Mouse.MouseY)
EndSub
```

**Comment by OmarTawfik** [comment]
This does look like a bug. Thanks for reporting!

unrelated tip: in markdown, multi-line code between single ticks "`" is not supported, it has to be three ticks "```" on their own lines:

```
code
```

**Comment by ozjerry** [comment]
Thanks for the tip Omar, and thanks also for all the hard work you're putting in!

**Comment by karroybb** [comment]
Hi @OmarTawfik, I was curious if Mouse.MouseY is supposed to measure from top of the window still? It seems like the position of the mouse relative to the big window will rarely be useful and Mouse.HideCursor() only works inside of the canvas as well. However, it also doesn't make sense to have duplicated functionality as GraphicsWindow.MouseY.

**Comment by OmarTawfik** [comment]
@karroybb  It can make sense in case you launched a game in your browser in full mode (F11). Otherwise, not much. What action do you suggest these utilities would do instead?

**Comment by Caseysch** [comment]
This is still being reported:

> I am writing a program to use mouse to draw something.  But, somehow, GraphicsWindow.MouseY does not give the exact y coordinate of where my mouse pointer is.  Graphics Window.MouseX is fine.  With a few tries, I found the GraphicsWindow.MouseX and GraphicsWindow.MouseY - 200 are pointing to where my mouse pointer is. Do you know what causes this issue and how I can fix it?
> 
> I seem to find out something about the issue. When I changed the zoom % of the browser, sometimes, the issue sent away.
>
