### ISSUE TITLE
V.1 Doesn't Support Opacity for Brush and Pen Colours

### ISSUE THREAD

**Issue by ozjerry** [sb/smallbasic-editor#57]
V1 doesn't allow the use of semi transparent colours, but V0.91 does.

Note the following code:
`GraphicsWindow.FillRectangle(50, 100, 100, 100)

GraphicsWindow.BrushColor = "#00FF0080"

GraphicsWindow.FillEllipse(100, 100, 100, 100)`

In v0.91 this will draw a semitransparent green circle over a mauve square. But in V1 it just draws a combined Move square and circle. It looks as if the colour definition is ignored.

**Comment by OmarTawfik** [comment]
@ozjerry does the desktop version support providing the alpha component as a 4th argument?
We should be looking into matching that for our first release, then go from there.

**Comment by OmarTawfik** [comment]
See #44 for more context as well.

**Comment by ozjerry** [comment]
@OmarTawfik, yes the desktop version supports alpha, but on desktop it is the first 2 digits as you mention in that other thread, rather than the last 2 as in SBV0.91.
Agree that you should go for consistency at first, but long term opinion would be to match the javascript/web implementation.  The web is likely going to be primary platform of the future, and a viable next step for students after SB would be something like [P5.JS](p5js.org). So conforming to the web standard would seem to be a good goal.

**Comment by OmarTawfik** [comment]
I'm wholeheartedly supporting going with RBGA instead of ARGB in this version (for the reasons you mentioned), but I'm not sure how many games would break because of that.
@EdPrice-MSFT any thoughts?

**Comment by OmarTawfik** [comment]
ping @EdPrice-MSFT 
Any thoughts on whether we should be supporting web standards moving forward? or sticking to the legacy windows values?

**Comment by Ed-Price** [comment]
@OmarTawfik Agree that we should go with RBGA (supporting web standards). As far as whether that will break legacy programs, let's inquire with the community council for a second opinion. I don't think it will be an issue, but we'll check.

**Comment by OmarTawfik** [comment]
Closed by #109
