### ISSUE TITLE
TextShapes should calculate their size from the pen size

### ISSUE THREAD

**Issue by OmarTawfik** [sb/smallbasic-editor#6]
Currently all text shapes have a fixed height/width in the Graphics window. These values should be calculated appropriately from `GraphicsWindow.FontSize` specified by the user.

**Comment by nonkit** [comment]
Text size in such as GraphicsWindow.DrawText, Shapes.AddText and other text are calculated by GraphicsWindow.FontSize in Small Basic Desktop.
