### ISSUE TITLE
Save File filename does not match the filename of the original Opened File

### ISSUE THREAD

**Issue by lucyajiang** [sb/smallbasic-editor#64]
If someone opens a file in SmallBasic, the filename is not stored. When they try to save the file, the filename is automatically set to "Program.txt" instead of the original filename. Is this the intended functionality, or is there a way to fix this so that the original filename is still accessible when someone wants to save their opened project?

**Comment by OmarTawfik** [comment]
There should be. This might be fixed on the JS side.
@lucjia why did you close it?

**Comment by lucyajiang** [comment]
I closed it because I found a way to fix it! I made it so that if they had opened one then the file name would save, but otherwise it would save to Program.txt

**Comment by OmarTawfik** [comment]
@lucjia great! do you want to submit a PR for the fix here?

**Comment by lucyajiang** [comment]
Hey Omar! Sorry for the late response, but I wanted to let you know that I submitted a PR about 10 hours ago.

**Comment by OmarTawfik** [comment]
@lucjia thanks :) will take a look now.

**Comment by lucyajiang** [comment]
Hi Omar, so sorry for not getting back to you! It’s finals week right now and I’ve been swamped but is it okay if I fix the problem by Thursday night? Thanks so much.

**Comment by OmarTawfik** [comment]
@lucjia no worries :) thanks so much for taking interest in this!

**Comment by lucyajiang** [comment]
Hi Omar - would you still like for me to change the file that you were talking about earlier? I see that the issue was closed 4 hours ago so just asking to make sure. Thanks!

**Comment by OmarTawfik** [comment]
@lucjia I found that it was because of an issue in the build script.
On build, we would update the lock file instead of matching it.
I fixed it, so that you don't get these updated locally if you don't add new packages.
Thanks for fixing this! 😄
