### ISSUE TITLE
Enter key doesn't work after some TextWindow.Read

### ISSUE THREAD

**Issue by nonkit** [sb/smallbasic-editor#66]
```
While "True"
    TextWindow.Write("Your name? ")
    name = TextWindow.Read()
    TextWindow.WriteLine("Hello " + name + "!")
EndWhile
```
1. Type the program above.
2. Push [Run] icon.
3. Type `Nonki` and hit [Enter] key.
4. Push [Back] icon.
5. Repeat instructions 2 to 4 three times.

**Comment by OmarTawfik** [comment]
@nonkit thanks for reporting! will submit a fix soon.
