### ISSUE TITLE
GraphicsWindow.Title causes syntax error

### ISSUE THREAD

**Issue by nonkit** [sb/smallbasic-editor#69]
Setting title like following code causes syntax error in SBO v1.0 but does nothing in SBO v0.91 ([https://smallbasic-publicwebsite.azurewebsites.net/Program/Editor.aspx](https://smallbasic-publicwebsite.azurewebsites.net/Program/Editor.aspx)).

```
GraphicsWindow.Title = "Hello!"
```

**Comment by nonkit** [comment]
`GraphicsWindow.Left` and `GraphicsWindow.Top` have the same behavior.  Sample code:
```
GraphicsWindow.Left = 0
GraphicsWindow.Top = 0
GraphicsWindow.DrawText(10, 10, GraphicsWindow.Left + ", " + GraphicsWindow.Top)
```

**Comment by OmarTawfik** [comment]
Because there are no windows in a browser, not a title to set :)
This was valid in the desktop editor, because a separate program is launched, not a part of your webpage.

**Comment by OmarTawfik** [comment]
Please feel free to reopen if you have thoughts on how this action can be feasible in a browser.

**Comment by nonkit** [comment]
Reason why I report this issue is that SBO v0.91 doesn't have this issue.

**Comment by OmarTawfik** [comment]
@nonkit but what would such a utility do in a browser? what is the proposal here? :)

**Comment by nonkit** [comment]
@OmarTawfik my proposals is that do nothing but be able to set/get GraphicsWindow.Title/Left/Top.  This will be allow to run many existing SBD programs.

(SBO v0.91 can set/get GraphicsWindow.Left/Top and can set GraphicsWindow.Title.  Silverlight version of SB can set/get GraphicsWindow.Left/Top/Title and work well like below.)

![Sample GW Title Left Top](https://user-images.githubusercontent.com/9944452/55470916-9559d200-5643-11e9-9a0f-4265e51136a0.png)

**Comment by OmarTawfik** [comment]
That makes sense. There is a few other tiny libraries that might work like that as well. I'll have to look into the rest.
