### ISSUE TITLE
ImageList.LoadImage causes syntax error

### ISSUE THREAD

**Issue by nonkit** [sb/smallbasic-editor#72]
Following sample causes syntax error:
```
' Sample Code for ImageList Object
TextWindow.Write("Image filename? ")
url = TextWindow.Read()
img = ImageList.LoadImage(url)
width = ImageList.GetWidthOfImage(img)
height = ImageList.GetHeightOfImage(img)
TextWindow.WriteLine("Size:" + width + "x" + height)
```

**Comment by OmarTawfik** [comment]
The error is:
`The library member 'ImageList.LoadImage' cannot be used in the online editor. Please download the desktop editor to use it.`
Currently we don't have a mechanism of shipping the desktop editor yet, but you can use it on your machine by building the repository and launching it from the build.

**Comment by nonkit** [comment]
@OmarTawfik I'd like to replace the sample code.  This issue should be fixed when this project is supporting desktop.
```
url = "http://www.nonkit.com/smallbasic.files/Turtle.png"
img = ImageList.LoadImage(url)
width = ImageList.GetWidthOfImage(img)
height = ImageList.GetHeightOfImage(img)
GraphicsWindow.DrawText(10, 10, "Size:" + width + "x" + height)
GraphicsWindow.DrawImage(img, 10, 30)
```
