### ISSUE TITLE
Confusing Cursor in Text Window

### ISSUE THREAD

**Issue by estberg** [sb/smallbasic-editor#77]
```
TextWindow.WriteLine("What is your name?")
name = TextWindow.Read()
```

After running these lines, the cursor for user input is at the beginning of a new line instead of the end of the prompt. 

<img width="393" alt="Screen Shot 2019-04-08 at 6 58 01 PM" src="https://user-images.githubusercontent.com/30135598/55768076-3d9adc80-5a30-11e9-8656-92109db1d7ac.png">

**Comment by Joseph-Schafer** [comment]
This does seem to be an issue if TextWindow.Write() is called. It makes sense that the cursor would drop with TextWindow.WriteLine() (since this is in effect a println command in Java) but
```
TextWindow.Write("What is your name?")
name = TextWindow.Read()
```
produces the same behavior of dropping the input to the following line.

**Comment by Joseph-Schafer** [comment]
Is it possible for users to change the output color mid-line? And should the read-in text be defaulted to the previous color?

**Comment by OmarTawfik** [comment]
@estberg thanks for reporting!
I think it might be an issue where [this](https://github.com/sb/smallbasic-editor/blob/fcd1eb22bf67b2756c993937bfd5e945a74756de/Source/SmallBasic.Editor/Components/Display/TextDisplay.cs#L112) html element is a block and not span-like. It will probably be a simple CSS fix to update it. Will look into it when I've some time next.

**Comment by OmarTawfik** [comment]
@Joseph-Schafer  Users can change the color midline. check the following program:
```
TextWindow.Write("AA")
TextWindow.ForegroundColor = "red"
TextWindow.Write("BB")
TextWindow.ForegroundColor = "green"
TextWindow.Write("CC")
TextWindow.ForegroundColor = "blue"
TextWindow.Write("DD")
TextWindow.ForegroundColor = "gray"
TextWindow.Write("EE")
TextWindow.ForegroundColor = "yellow"
TextWindow.WriteLine("")
```

**Comment by OmarTawfik** [comment]
Thanks @estberg for reporting. Fixed now.
